all:
	minSum, minPath, totalPos, subSet
minSum:
	g++ -o minSum minSum.cpp
minPath:
	g++ -o minPath minPath.cpp
totalPos:
	g++ -o totalPos totalPos.cpp
subSet:
	g++ -o subSet subSet.cpp
clean:
	rm -f minPath minSum totalPos subSet